
# API Key for general usage
tmdb.api.key=be48c7bb8ff905c55cbd9430e1a5e934

# Base URL for TMDB API
tmdb.api.base-url=https://api.themoviedb.org/3

# Base URL for TMDB image resources
tmdb.api.image-base-url=https://image.tmdb.org/t/p/w500